when:
  - event: push
    branch: [main, releases/*]
  - event: pull_request


clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 1
      lfs: false
      tags: true

steps:
  check:
    image: python:${TAG}-bullseye
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install tox setuptools setuptools_scm[toml]
      - python -m tox -e py


matrix:
  TAG:
    - 3.9
    - 3.10
    - 3.11
    - 3.12
    - 3.13
